// import logoSvg from "@/assets/images/logo.svg";
// import logoSmSvg from "@/assets/images/logo-sm.svg";

module.exports = [
    {
        clientId: "bimatic.net",
        name: "Bimatic",
        primaryStart: "#F0B90B",
        primaryEnd: "#F0B90B",
        primary: "#F0B90B",
        secondary: "#181A20",
        secondaryLanding: "#181A20",
        secondarySidebar: "#181A20",
        landingStyle: 2,
        logoSvg: "/assets/images/logo.svg",
        logoSmSvg: "/assets/images/logo-sm.svg",
        iconWin: "/assets/images/icon-win.png",
        contactEmail: "contact@bimatic.net",
    },
    {
        clientId: "firecoin.trade",
        name: "Firecoin",
        primaryStart: "#fb7617",
        primaryEnd: "#fb7617",
        primary: "#fb7617",
        secondary: "#181A20",
        secondaryLanding: "#181A20",
        secondarySidebar: "#181A20",
        landingStyle: 2,
        logoSvg: "/assets/images/logo.png",
        logoSmSvg: "/assets/images/logo.png",
        iconWin: "/assets/images/icon-win.png",
        contactEmail: "contact@firecoin.trade",
    },
    {
        clientId: "woodex.vip",
        name: "Woodex",
        primaryStart: "#ef4144",
        primaryEnd: "#A05618",
        primary: "#ef4144",
        secondary: "#181A20",
        secondaryLanding: "#181A20",
        secondarySidebar: "#181A20",
        landingStyle: 1,
        logoSvg: "/assets/images/logo-wd.png",
        logoSmSvg: "/assets/images/logo-wd.png",
        iconWin: "/assets/images/icon-win-wd.png",
        contactEmail: "contact@woodex.vip",
    },
    {
        clientId: "localhost",
        name: "Localhost",
        primaryStart: "#ef4144",
        primaryEnd: "#A05618",
        primary: "#ef4144",
        secondary: "#181A20",
        secondaryLanding: "#181A20",
        secondarySidebar: "#181A20",
        landingStyle: 1,
        logoSvg: "/assets/images/logo-wd.png",
        logoSmSvg: "/assets/images/logo-wd.png",
        iconWin: "/assets/images/icon-win-wd.png",
        contactEmail: "contact@woodex.vip",
    },
    {
        clientId: "192.168.1.191",
        name: "Localhost",
        primaryStart: "#ff592c",
        primaryEnd: "#ff592c",
        primary: "#ff592c",
        secondary: "#011022",
        secondaryLanding: "#141416",
        secondarySidebar: "#011022",
        landingStyle: 2,
        logoSvg: "/assets/images/logo.svg",
        logoSmSvg: "/assets/images/logo-sm.svg",
        iconWin: "/assets/images/icon-win.png",
        contactEmail: "contact@localhost",
    },
];
